# Generated by Django 5.1.2 on 2024-10-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.device')),
            ],
            bases=('shop.device',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.device')),
            ],
            bases=('shop.device',),
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.device')),
            ],
            bases=('shop.device',),
        ),
        migrations.AlterField(
            model_name='device',
            name='_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
    ]
