# Generated by Django 5.1.2 on 2024-10-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_laptop_smartphone_tablet_alter_device__stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.device')),
            ],
            bases=('shop.device',),
        ),
    ]
