# Generated by Django 5.1.2 on 2024-10-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_generic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tablet',
        ),
    ]
