# Generated by Django 5.1.2 on 2024-10-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_tablet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.device')),
            ],
            bases=('shop.device',),
        ),
    ]
