# Generated by Django 5.1.2 on 2024-10-12 14:47

import filemanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_uploadedfile_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=filemanager.models.file_directory_path)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
